### ISSUE TITLE
Question about Transaction Fee

### ISSUE THREAD

**Issue by SleepingNext** [polkadot-js/docs#107]
Hello. Thank you for reading this issue. Is that possible for a transaction to cost nothing in Polkadot or Westend? For example, sending some DOTs or WNDs to a parent address (The address that derives an address) costs zero fees. Any comments or suggestions are accepted. Thanks in advance!

**Comment by shawntabrizi** [comment]
You should check out this video on how you can make feeless transactions in Substrate:

https://www.youtube.com/watch?v=7GOd2g4JZqg

**Comment by SleepingNext** [comment]
Thank you!
