### ISSUE TITLE
wallet-error

### ISSUE THREAD

**Issue by lijianl** [polkadot-js/docs#119]
could you help with the error:

```
createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding staking.submitElectionSolutionUnsigned:: Struct: failed on args: {"winners":"Vec<ValidatorIndex>","compact":"CompactAssignments","score":"ElectionScore","era":"EraIndex","size":"ElectionSize"}:: Maximum call stack size exceeded
```

and as for `Maximum call stack size exceeded`, do API has some limit? how to solve

**Comment by jacogr** [comment]
Which network and block? 

The above indicates that the type the API believes the structure to be and what it is on the node is mismatched.

**Comment by jacogr** [comment]
Closing, no further information provided as requested. (The 3.5.1 release actually had a fix for a similar issue, may be applicable here - https://github.com/polkadot-js/api/issues/3055)
