### ISSUE TITLE
Error: account balance too low  

### ISSUE THREAD

**Issue by lijianl** [polkadot-js/docs#132]
transfer dot error:

`
Error: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
`

fromAddress has amount 1dot

```js
// params= > fromkey, toaddr, (10000000000 - 154000000)
async function test_sendDotWithRpc(fromKey, toAddr, amount) {
    await api.isReady;
    let keyring = new Keyring();
    let suri = fromKey;
    let pair = keyring.addFromUri(suri);
    // single
    let transfer = api.tx.balances.transfer(toAddr, amount);
    let txhash = await transfer.signAndSend(pair, { nonce: -1 }).catch(console.error);
    console.log('txhash->', txhash.toHex(), amount);
}
```

could I get any more information for what happened?
why this error

**Comment by jacogr** [comment]
You need to have funds to pay pay the fees. After application of the fees, the balance cannot be below the existential amount - which is 1 DOT.

So to transfer you need to have at least existential + fees available. (1 DOT + fees)

**Comment by lijianl** [comment]
> You need to have funds to pay pay the fees. After application of the fees, the balance cannot be below the existential amount - which is 1 DOT.
> 
> So to transfer you need to have at least existential + fees available. (1 DOT + fees)

thanks, get it
