### ISSUE TITLE
How to generate api files from substrate-based chain

### ISSUE THREAD

**Issue by MyronFanQiu** [polkadot-js/docs#146]
Hello, we're building a substrate-based chain and we want to export all extrinsics/storage apis to docs, just like this file https://github.com/polkadot-js/docs/blob/master/docs/substrate/extrinsics.md. I checked the content of the summary and it's same with the comments in the rust code. How can I generate this doc file from rust code? 😄

**Comment by MyronFanQiu** [comment]
@jacogr Hi, could you shed light on this question?

**Comment by jacogr** [comment]
It is purely done for Substrate master docs via the metadata/v12/static.ts file while is refreshed more-or-less weekly. There is no command that allow overrides.

**Comment by MyronFanQiu** [comment]
> It is purely done for Substrate master docs via the metadata/v12/static.ts file while is refreshed more-or-less weekly. There is no command that allow overrides.

Thanks for the reply. We don't want to do any change for the current doc. We want to build our own doc for our chain. You mentioned this file https://github.com/polkadot-js/api/blob/master/packages/metadata/src/v12/static-substrate.json is refreshed weekly. I believe there should be some code to generate this file, is that correct? Is the code integrated in some CI or CD task so that I can check the logic how to generate the metadata doc?

**Comment by jacogr** [comment]
It is all done manually.

**Comment by MyronFanQiu** [comment]
> It is all done manually, update the hex data, generate the JSON, check for new fields, compare types, there is no refresh CI task. (For docs this means updating the docs dependencies and running the generator which builds from the hex data - https://github.com/polkadot-js/api/blob/master/packages/typegen/scripts/polkadot-types-internal-metadata.cjs)

![image](https://user-images.githubusercontent.com/49134743/115373204-3d786e80-a1fe-11eb-81b8-31b3d8a3d61a.png)
We can see the detail explanation for each extrinsic on apps. I checked the sentence and it should come from chain(rust code) directly. Do you mean that's from the metadata which were built manually? The question is, even for the special extrinsic built by us in our chain, we can see the explanation as well. But we didn't do any update for the metadata. Our target is to generate a doc for our chain to include all extrinsic, error, event and storage. Looks like apps can read the comments in substrate automatically and show them to the users. Do you know the reason or point to some code fraction we can check?

**Comment by jacogr** [comment]
That is exactly the metadata. The above script reads the hex metadata to extract.

**Comment by MyronFanQiu** [comment]
> That is exactly the metadata. The above script reads the hex metadata to extract.

Thank you very much. So how to obtain or get the hex data for a chain?

**Comment by MyronFanQiu** [comment]
Find the way to obtain hex data. Thanks very much!
