### ISSUE TITLE
Polkadot.js Issues. 

### ISSUE THREAD

**Issue by CRYPTOMONEYMIKE** [polkadot-js/docs#153]
When trying to claim my Pswap i keep getting this error. Im logged in with my ledger but it keeps giving me this error msg. Any input appreciated.

Something went wrong with the query and rendering of this component. Unable to find supported chain for 0x7e4e32d0feafd4f9c9414b0be86373f9a1efa904809b683453a9af6856d38ad5

**Comment by jacogr** [comment]
Since you mentioned Ledger - it only has apps for Polkadot, Kusama, Dock and Polyhash. Any other chains don’t have Ledger apps.

**Comment by CRYPTOMONEYMIKE** [comment]
i was trying to use polkaswap hooked up to my ledger. Under the tab rewards you can claim pswap for being a xor/sora LP. but for some reason i cant claim the rewards bc the error keeps popping up.Sent from my Galaxy
-------- Original message --------From: Jaco ***@***.***> Date: 2021-04-30  11:12  (GMT-08:00) To: polkadot-js/docs ***@***.***> Cc: CRYPTOMONEYMIKE ***@***.***>, Author ***@***.***> Subject: Re: [polkadot-js/docs] Polkadot.js Issues.  (#153) 
What is pswap?

**Comment by jacogr** [comment]
Sora does not have Ledger app support. As per above it is limited to other chains only.
