### ISSUE TITLE
Failed on the first time with a simple example

### ISSUE THREAD

**Issue by tiendq** [polkadot-js/docs#166]
Just running a docker node and run a simple example here https://polkadot.js.org/docs/api/start/create

```
const { ApiPromise, WsProvider } = require('@polkadot/api');

const wsProvider = new WsProvider('ws://127.0.0.1:9944');

(async () => {
  const api = await ApiPromise.create({ provider: wsProvider });

  // Do something
  console.log(api.genesisHash.toHex());
})();
```

Got tons of strange errors :(

```
2021-05-27 15:08:27        REGISTRY: Unable to resolve type ChainId, it will fail on construction
2021-05-27 15:08:27        REGISTRY: Unable to resolve type DepositNonce, it will fail on construction
2021-05-27 15:08:27        REGISTRY: Unable to resolve type ResourceId, it will fail on construction
2021-05-27 15:08:27        API/INIT: Error: FATAL: Unable to initialize the API: createType(ChainId):: Cannot construct unknown type ChainId
```

**Comment by jacogr** [comment]
That is a customized node. Which means types have been added on the Rust side. There is no type reflection capabilities in the metadata yet. 

So this is not a simple example, but rather one where the node has been customized. Please see the devotions on injecting additional types (that does not exist on Substrate master) into your JS API so it knows how to handle it.  

You will need to inject it each of the unknown types such as ChainId….

**Comment by tiendq** [comment]
Ok, so if I have a local edgeware node like this https://github.com/hicommonwealth/edgeware-contracts-tutorials/blob/master/4/setting-up-a-local-node.md

How can I make this code snippet work? Or it simply doesn't support.

**Comment by jacogr** [comment]
Edgeware publishes their own type definitions on NPM that is to be used with the API to inject the types for that type of node - https://github.com/hicommonwealth/edgeware-node-types
