### ISSUE TITLE
code.createBlueprint is not a function

### ISSUE THREAD

**Issue by bostontrader** [polkadot-js/docs#174]
Hello, I'm trying to work through the examples at https://polkadot.js.org/docs/api-contract/start/code/ and am getting the error "code.createBlueprint is not a function"

I'm using  "@polkadot/api-contract": "^4.13.1" 

I'm using ink! and attempting to work with the incrementer example contract.

I am using an unmodified substrate canvas chain. 

I can execute  const code = new CodePromise(api, abi, wasm);  without any error.

I'm using var abi = HERE DOC about 300 lines of JSON text from incrementer's metadata.json file and this appears to parse correctly.

I'm using var wasm = "0x... about 36K of hex" from incrementer.contract and this also appears to be working correctly. 

If I search the source code for createBlueprint I see about 10 references to createBluePrintTx, but if I try to use this method instead, I get the same error.

Any clues greatly appreciated.  Thanks!

**Comment by jacogr** [comment]
Docs need updating (I'm guessing here), the `createBlueprint` and other items have been deprecated for a very long time.

**Comment by jacogr** [comment]
Closing, the deprecations tracked in #172
