### ISSUE TITLE
Creating enums using `createType`

### ISSUE THREAD

**Issue by maltekliemann** [polkadot-js/docs#223]
It seems like enums types like this one...

```json
"MyEnum": {
  "_enum": {
    "member": "u32",
    ...
  }
}
```

...are created using the following pattern:

```js
let enum = api.createType("MyEnum", {"member": value});
```

Is this correct? If so, I think this is missing from the docs.

**Comment by jacogr** [comment]
The above is correct. PRs welcome to update the docs.
