### ISSUE TITLE
How to get transaction hash?

### ISSUE THREAD

**Issue by NetGodFather** [polkadot-js/docs#226]
How to obtain the transaction hash of transactions created through “api.tx.utility.batchAll(calls)” after they are in block.

**Comment by NetGodFather** [comment]
Code like this :
	const batchExtrinsic = api.tx.utility.batchAll(calls);
	await batchExtrinsic.signAndSend(sender, ({ events = [], status }) => { ... } );

**Comment by jacogr** [comment]
Please don't log the same issue across multiple repos, it actually adds overload to the system and takes me longer to actually get there since I now need to wade through double the amount of issues.
