### ISSUE TITLE
A query to get transfer date 

### ISSUE THREAD

**Issue by MojtabaMohammadzadeh** [polkadot-js/docs#293]
I searched all of the storage queries in doc and there is not any query to get date and time of a specific transfer . just timestamp that has two option . didupdate and now 
I need to know how can I get date and time that a transfer happened

**Comment by jacogr** [comment]
All blocks contain a timestamp.set - https://polkadot.js.org/docs/substrate/extrinsics#setnow-compactu64 - it is included by the block author.
