### ISSUE TITLE
Question: add documentation for substrate objects used in API params 

### ISSUE THREAD

**Issue by muddlebee** [polkadot-js/docs#315]
Link -> https://polkadot.js.org/docs/substrate/storage/#assets
![Screenshot 2022-06-27 at 11 51 53 PM](https://user-images.githubusercontent.com/8139783/176011774-51378536-c1e3-49b7-b473-e7025d0351d9.png)

AccountId32 above as an example. I went through some of the docs to find something substantial in substrate docs
1. https://paritytech.github.io/substrate/latest/sp_runtime/struct.AccountId32.html#
2. at polkadot sidecar, in swagger the data objects/model has explanation https://paritytech.github.io/substrate-api-sidecar/dist/

Can we add such information to docs?

**Comment by jacogr** [comment]
See this for the relevant work required - https://github.com/polkadot-js/api/issues/4845

It is entirely possible, however there are a lot of tweaks required and for that there needs to be hands on keyboard, so PRs that move this forward would be the best approach.
