### ISSUE TITLE
Derives are not covered

### ISSUE THREAD

**Issue by vikiival** [polkadot-js/docs#335]
[Detour into derives](https://polkadot.js.org/docs/api/start/api.rpc#detour-into-derives) states:

> The api.derive interfaces will be covered in a follow-up section

However there is no follow-up section 🥹

**Comment by jacogr** [comment]
Those are tricky - trying to keep those current would be a nightmare since it really is into undocumented and very unstable territory.

**Comment by vikiival** [comment]
> really is into undocumented and very unstable territory.

Maybe just mention the commonly used ones in the cookbook?

```ts
const { availableBalance } = await api.derive.balances.all(address)

// instead of 

const { data: { free: availableBalance } } = await api.query.system.account(address)
```

I think there could be many more that I am not aware of.


Btw: I will be happy to write it down.
