### ISSUE TITLE
Information relating to values returned from query.auctions.auctionInfo()

### ISSUE THREAD

**Issue by alfarok** [polkadot-js/docs#355]
My question is what are the 2 array values that are returned from invoking `query.auctions.auctionInfo(SOME_HASH)`?  I originally believed the first integer in the array to be the number of `AuctionLeasePeriods` and the second integer to be the `AuctionEndingBlockNumber`.  This logic seemed to align for Polkadot as the `AuctionLeasePeriods` was never greater than 8 (8x 12 week periods or 96 weeks).  On Kusama I see larger integers.  I expected this also to be capped at 8 (8x 6 week periods or 48 weeks).

![image](https://user-images.githubusercontent.com/13341935/192496820-4e218038-cdab-44b8-b9da-215514b9a995.png)

For example, the first auction on Kusama starts at [Block #7924237](https://kusama.subscan.io/block/7924237)

so invoking `query.auctions.auctionInfo(0x76cd95e9279ad833572427a959faa0c85ff99c8e543dc22f940279d42693f903)`

returns `[13, 7951237]`

where [Block #7951237](https://kusama.subscan.io/block/7951237) is the auction ending block but I can't figure out what the 13 is in reference to?

Thanks!

**Comment by alfarok** [comment]
Upon closer investigation I can see I am misinterpreting the first value in this returned array.  It does exceed 8 in later Polkadot auctions too so it is not the `AuctionLeasePeriods`, naive mistake.  Either way I am still curious what this value represents.  Thanks again!

**Comment by jacogr** [comment]
The source of truth is here - https://github.com/paritytech/polkadot/blob/6b67d8654d11c1edbced73cb9f98e39d953b2900/runtime/common/src/auctions.rs#L181-L188

```rust
	/// Information relating to the current auction, if there is one.
	///
	/// The first item in the tuple is the lease period index that the first of the four
	/// contiguous lease periods on auction is for. The second is the block number when the
	/// auction will "begin to end", i.e. the first block of the Ending Period of the auction.
	#[pallet::storage]
	#[pallet::getter(fn auction_info)]
	pub type AuctionInfo<T: Config> = StorageValue<_, (LeasePeriodOf<T>, T::BlockNumber)>;
```

**Comment by alfarok** [comment]
Perfect, appreciate the info!
