### ISSUE TITLE
You need to provide at least one example for "Working with Option<Type>"

### ISSUE THREAD

**Issue by rlaferla** [polkadot-js/docs#356]
You need to provide at least one example for "Working with Option<Type>"

https://github.com/polkadot-js/docs/edit/master/docs/api/start/types.basics.md

**Comment by jacogr** [comment]
Not sure what this means since the option has descriptions of the specific methods - however leaving it open, there may be a taker for a PR to clarify.

**Comment by jacogr** [comment]
Closing, since we have https://polkadot.js.org/docs/api/start/types.basics#working-with-optiontype
