### ISSUE TITLE
How to decorate API with Typegen

### ISSUE THREAD

**Issue by decentration** [polkadot-js/docs#357]
Hi there i left a question on substrate stackechange related to Typegen. 

Link to question: https://substrate.stackexchange.com/questions/5024/how-to-use-polkadot-js-typesript-typegen-to-decorate-api-for-runtime

The questions are:

- is typegen still up to date and something that can be used to decorate APIs?
- has endpoint been removed as an argument?
- am i going about thing the correct way to decorate the api?

**Comment by decentration** [comment]
Hey @jacogr, i know you are busy, can you point me in the right direction in regard to this. I am getting an issue with the `endpoint` method...

**Comment by decentration** [comment]
hi @jacogr, just checking to see if you can provide any support here?

**Comment by decentration** [comment]
any support or clarity would be super useful

**Comment by decentration** [comment]
Any support here?

**Comment by woss** [comment]
> Any support here?

i hope this will help you https://github.com/anagolay/anagolay-js-sdk/blob/main/libraries/types/package.json#L43 we are using it like this

**Comment by decentration** [comment]
ahoy! thanks for responding. It would also be great if you could answer the stack exchange issue, with a few steps.

**Comment by woss** [comment]
@decentration what kind of steps would you require?

**Comment by woss** [comment]
@decentration https://substrate.stackexchange.com/questions/5024/how-to-use-polkadot-js-typescript-typegen-to-decorate-api-for-runtime/6359#6359 here you have it

**Comment by decentration** [comment]
thanks @woss, that helped add a missing piece.

**Comment by woss** [comment]
i guess you can close thie @decentration if it's answered in the stacexchange
