### ISSUE TITLE
keyring.getAccounts is not a function

### ISSUE THREAD

**Issue by magus777** [polkadot-js/docs#363]
The API documentation is terrible and doesn't explain basic things such as - how to create an account. Where is it saved?
When I use the Polkadot.js App on my home computer I see the accounts are saved in the directory polkadot-accounts.
When I use the API on my server I don't see the account being saved anywhere. Is it saved in the keyring? It seems like that only exists in memory. Does the keyring save a copy of the accounts in the same format as the App ?
When you create a new account using the App, it is saved in this format:

{"encoded":"DBSPyMN8LAWsoejHHMfqU2/m5YxxeGtD0HJpzQzyY44AgAAAAQAAAAgAAADug5JmpYwzc9oxUJXUY2zIWkZFQRtqoS3lgu/wdhRSLPwx5TKjaMRrIqrrSyO3uxRytoPmKT5wTDV/zGyh2S9xwozzqhQhBmJG7TJwA+oNqDKpQpj6cooWNSivRzKmpqPaMO+af0LPPOREvVGHESwBSf+xHMZ5fISIG97xbXhGXV89Oo4iEBSwpIhjz6+u7AiVtF2akpyxLkhqiIXC","encoding":{"content":["pkcs8","sr25519"],"type":["scrypt","xsalsa20-poly1305"],"version":"3"},"address":"14BrSo66a3zvZmTksQFBmtZYEHvyWGJEBQypVfDynPXbsz2T","meta":{"genesisHash":"0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3","isHardware":false,"name":"POLKY123TESTONLY","tags":[],"whenCreated":1665704506323}}

Is a file like this created and saved to disk when this function is called?
const pair = keyring.addFromUri(mnemonic, { name: 'POLKA_KEY_'+randomName }, 'ed25519');

?

When I do this simple task I get the error: keyring.getAccounts is not a function

import { u8aToHex } from '@polkadot/util';
import { Keyring } from '@polkadot/keyring';
import { mnemonicGenerate } from '@polkadot/util-crypto';

// create a keyring with some non-default values specified
const keyring = new Keyring({ type: 'sr25519', ss58Format: 2 });

const accounts = keyring.getAccounts();

accounts.forEach(({ address, meta, publicKey }) =>
  console.log(address, JSON.stringify(meta), u8aToHex(publicKey))
);

which is odd because this works fine:

const pair = keyring.addFromUri(mnemonic, { name: 'POLKA_KEY_'+randomName }, 'ed25519');

so the keyring addFromUri function works fine but getAccounts() doesn't ?

I am totally confused just trying to simply make an account, save it and reload it again.
In Ethereum & Bitcoin I could find a hundred webpages describing how to do this in detail. I can't find any decent documentation describing how to do this.

If I do:

console.log(Object.getOwnPropertyNames(keyring))

I get:

[ 'decodeAddress', 'encodeAddress' ]

? How do I access the getAccounts function? It appears to be missing

**Comment by jacogr** [comment]
PRs to improve the documentation is always very welcome.

There is no `getAccounts()`, so the error is certainly correct. You are most-probably looking for `getPairs()` - https://github.com/polkadot-js/common/blob/2c1efaa7a0ceead10d8333bd7eb511c1c382506c/packages/keyring/src/keyring.ts#L262-L269

The keyring itself has no backing store. There is a [UI -specific variant](https://github.com/polkadot-js/ui/tree/master/packages/ui-keyring) that takes an optional [backing store](https://github.com/polkadot-js/ui/tree/master/packages/ui-keyring/src/stores)
