### ISSUE TITLE
Is there any method for domain lookup?

### ISSUE THREAD

**Issue by ishan501** [polkadot-js/docs#371]
Hi, I'm looking for a domain lookup method. But, could not find it in the documentation. Can anyone help with this?

**Comment by jacogr** [comment]
The api only exposes what is in the runtime. It does this via [metadata](https://polkadot.js.org/docs/api/start/basics#metadata) supplied from the runtime that it retrieves when connecting.

There may be chains that have some "domain lookup pallets" where the methods then would be exposed, I don't know of any off-hand.
