### ISSUE TITLE
Where is Bob's Address comming from?

### ISSUE THREAD

**Issue by FrankBevr** [polkadot-js/docs#443]
### Problem

I ran `./node-template key inspect //Bob`
But nothing is the same as [Dev Accounts Link](https://polkadot.js.org/docs/api/examples/promise#development-accounts)

So Bob is only a PolkaJS thing.
Currently and can be generated thruh.
```ts
import { WsProvider, ApiPromise, Keyring } from '@polkadot/api'

const wsProvider = new WsProvider();
const api = await ApiPromise.create({provider: wsProvider})

async function getBobAndSendTransaction(){
  await api.isReady
  const keyring = new Keyring({type:"sr25519"})
  const alice = keyring.addFromUri("//Alice")
  const bob = keyring.addFromUri("//Bob")
  const BOB = bob.address
  const transfer = api.tx.balances.transfer(BOB, 12345)
  const hash = await transfer.signAndSend(alice)
  console.log(hash)
}
```

Took me a while to understand where is it comming from.

### Solution
Add a small paragraph to [Dev Accounts](https://polkadot.js.org/docs/api/examples/promise#development-accounts) and add Link in [this section](https://polkadot.js.org/docs/api/start/api.tx.subs#transaction-inclusion)
Maybe a small explainer how bob is generated or what node-template bob differenciate from polkaJS bob.

**Comment by jacogr** [comment]
“Bob” is not a Polkadot-JS “thing”. 

It is a standard Substrate dev account.

**Comment by FrankBevr** [comment]
But why I get a diffrent output?

`./substrate-contracts-node key inspect //Alice`
gives me this output
```
Secret Key URI `//Alice` is account:
  Network ID:        substrate
 Secret seed:       0xe5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a
  Public key (hex):  0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d
  Account ID:        0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d
  Public key (SS58): 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
  SS58 Address:      5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
  ```
  
  and in the PolkadotJS Wiki I found this, which works nicely. [LinkToSection](https://polkadot.js.org/docs/api/examples/promise#development-accounts)
  ```
Alice: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
Bob: 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
  ```
  

Oh... Ok forget what I just said. 
I did something wrong, maybe copy paste falsely.

Now I'm getting red ^^

Thanks mate 💯
