### ISSUE TITLE
How to add or modify typegen templates (.hbs files)

### ISSUE THREAD

**Issue by Muhammad-Altabba** [polkadot-js/docs#459]
What is the supported way to add or modify typegen templates (.hbs files)? Could you please add this to the docs:
https://polkadot.js.org/docs/api/examples/promise/typegen/?

If it is not supported currently, could you please give a hint on the best way to do it?

Thanks,

**Comment by jacogr** [comment]
It is baked into the typegen repo.

If you wish to supply options for it, you can -

1. Fork the api repo and make your changes
2. Make a PR to add configuration options to the cli to support this
