### ISSUE TITLE
FAQ link (linked from search engine) 404s

### ISSUE THREAD

**Issue by jimmychu0807** [polkadot-js/docs#55]
Reported by @apopiak
This link (https://polkadot.js.org/api/start/FAQ.html) 404s, but it's one of the top results when searching for "polkadot.js.org troubleshooting". Maybe missing a redirect to https://polkadot.js.org/docs/api/FAQ?

**Comment by wheresaddie** [comment]
can this be pushed to a redirect on the DNS side .. ?

**Comment by jacogr** [comment]
Added a gh-pages 404, it now redirects.

**Comment by wheresaddie** [comment]
thanks @jacogr
