### ISSUE TITLE
Issues while reading from the contract via an RPC call 

### ISSUE THREAD

**Issue by AthulTony** [polkadot-js/docs#69]
Hi, I am new to the substrate and Polkadot.

I followed the below link to read from the contract via an RPC call.
https://polkadot.js.org/docs/api-contract/start/contract.read/
The contract deployed is the flip contract that flips the boolean value.
https://substrate.dev/substrate-contracts-workshop/#/0/setup

The contract has been successfully deployed and the flip function was called. I am getting all results in Explorer block details.
But trying to retrieve the contract value by node js gives me output as null and message: 'NotCallable'.

Read from the contract via an RPC call 
result_1 :  {"debugMessage":"","gasConsumed":0,"output":null,"result":{"Err":{"Module":{"index":17,"error":12,"message":"NotCallable"}}}}
gasConsumed :  0
result :  { Err:
   { Module: { index: '17', error: '12', message: 'NotCallable' } } }
Error Type {
  registry: MetaRegistry { metaTypeDefs: [ [Object] ] },
  isOther: [Getter],
  asOther: [Getter],
  isCannotLookup: [Getter],
  asCannotLookup: [Getter],
  isBadOrigin: [Getter],
  asBadOrigin: [Getter],
  isModule: [Getter],
  asModule: [Getter] }

.

**Comment by jacogr** [comment]
So that error comes via the contracts interface itself. (index = 17 is the contracts palette). The `NotCallable` is weird, never seen that before, not know the causes for it. (So will need to have some investigation into the actual substrate palette code to understand under what condition it occurs)
