### ISSUE TITLE
system.events() does not take any arguments

### ISSUE THREAD

**Issue by SleepingNext** [polkadot-js/docs#72]
Hello. I just tried the example given in this link: https://polkadot.js.org/docs/api/cookbook/blocks on the question: "How do I map extrinsics to their events?". The line below:
`const allRecords = await api.query.system.events(signedBlock.block.header.hash);`
seems to need to be changed since system.events() does not take any arguments (Please see image below).
![image](https://user-images.githubusercontent.com/42561768/98802807-6a9e4500-2446-11eb-9c81-fd3e5596d179.png)

Furthermore, how can I get events of a specific block?

**Comment by jacogr** [comment]
Via `.at(<blockHash>)`, https://polkadot.js.org/docs/api/start/api.query.other#state-at-a-specific-block

**Comment by SleepingNext** [comment]
@jacogr, how about the code I mentioned above? Will it be updated? Thank you.

**Comment by jacogr** [comment]
`system.events()` does not take arguments, so the above definition is correct. (As is the error message, arguments are only available/exposed on maps and doublemaps)

As per the linked docs, it you need a specific blockhash, `await api.query.system.events.at(<blockHash>)`

**Comment by jacogr** [comment]
Ahh, I see now what you mean, yes the docs are wrong there... :( It followed the approach for RPC. Good catch.

**Comment by SleepingNext** [comment]
Great! Thank you.
