### ISSUE TITLE
Ambiguous Sentence

### ISSUE THREAD

**Issue by SleepingNext** [polkadot-js/docs#76]
Hello, I'm sorry if this is due to my lack of knowledge. But, I'm kinda confused with the information provided by https://polkadot.js.org/docs/ui-keyring/start/init in the Create section. It firstly said that the default value is sr25519. But, at the end of the sentence, it says the default value is ed25519 (Please the image attached in this issue). If the default is ed25519, you might consider saying: "Sets up the default account type to sr25519", just like the above one did. Thank you very much :)

![image](https://user-images.githubusercontent.com/42561768/99357192-15e34a00-28de-11eb-939b-d80318f9e483.png)

**Comment by SleepingNext** [comment]
Is the documentation need to be changed? Thanks.

**Comment by jacogr** [comment]
Yes, indeed, the last one needs to be sr.

**Comment by SleepingNext** [comment]
Okay, I will a PR, then.
