### ISSUE TITLE
Adding Search

### ISSUE THREAD

**Issue by apopiak** [polkadot-js/docs#78]
I would like to be able to search the documentation on the site.

**Comment by SleepingNext** [comment]
I would really love that feature too.

**Comment by jacogr** [comment]
I'll paste what I has as a local message -

"
M
i'm just thinking about adding a search to the upcoming xxx-docs docusaurus. unfortunately the easiest way is a free third party service called algolia. from a privacy perspective this seems suspicious.

have you decided consciously not to include search in the polkadot-js docs for this reason?
"

"
Jaco
Yes.
However, there is a local-only option https://github.com/daldridge/docusaurus-plugin-lunr
And this one, https://github.com/lelouch77/docusaurus-lunr-search
Now sure which is which and how any of it works. But that won't happen anytime soon.
But, there may be server-less options.
"

PRs for anything local-only welcome as a test.

**Comment by chrisdcosta** [comment]
@jacogr isn't the text search as mentioned [here](https://docsify.js.org/#/plugins?id=full-text-search) useful?

**Comment by jacogr** [comment]
The above looks like `docsify`, not `docusaurus`.

**Comment by hamidra** [comment]
I find google advanced search a good workaround till a good local search solution is found:
use site:polkadot.js.org/docs to scope your google search to polkadot.js.org/docs

e.g.
https://www.google.com/search?q=%22api.registry%22+site%3Apolkadot.js.org%2Fdocs

**Comment by guoyupeng01** [comment]
I would really love that feature too.

**Comment by Akagi201** [comment]
Hey guys, I am integrating algolia's docsearch into this site.

**Comment by jacogr** [comment]
Closing, we have it in after https://github.com/polkadot-js/docs/pull/310 (Thanks to @SaltyCucumber)
