### ISSUE TITLE
Question About Private Key and Derivation

### ISSUE THREAD

**Issue by SleepingNext** [polkadot-js/docs#82]
Hello. I'm really sorry if this is due to my lack of knowledge. After reading the documentation for a few days, I still have some questions in my head.

1. Assume that I have mnemonic words. And then, I use the `mnemonicToMiniSecret(mnemonic)` function to create a `seed`. After that, I use the `schnorrkelKeypairFromSeed(seed)` function to create a `keyPair`. From the `keyPair`, I can have a `publicKey` that has the same value as the `publicKey` that I can have from the `createFromUri(mnemonic)` function, and also a `secretKey`. My question is, "Is the `secretKey` actually a `privateKey` that can be used for signing a transaction?". I'm asking this because I need to save the `privateKey` of the account that I created.

2. This question is a bit related to the first one. Assume that the first question is answered with a "Yes". In Polkadot, is it possible to use the `privateKey` of an account as an `xprv` to generate a `childPrivateKey`? What I'm talking about is kind of deriving an account via the `privateKey` of its parent.

3. This question is related to the previous one. Assume that the previous question is answered with a "Yes". Is that also possible to get the `privateKey` of that derived account?

Again, I'm really sorry if this is due to my lack of knowledge. Thanks in advance! :smile:

**Comment by jacogr** [comment]
1. Yes.

2. Yes.

3. Yes.

Derivations are done in the keyring itself, but the sr25519Derive and friends are exposed. It just takes a path along with the key and returns a new pair.

**Comment by SleepingNext** [comment]
Hm... How can I derive an account using a private key, sir @jacogr?  I mean, what are the functions that I need in order to do that? Thank you.

**Comment by jacogr** [comment]
I mentioned sr25519Derive, see here - https://github.com/polkadot-js/common/tree/master/packages/util-crypto/src/schnorrkel

(It is not documented and won't be, since it exists on a pair https://github.com/polkadot-js/common/blob/master/packages/keyring/src/pair/index.ts#L147 when using the keyring, the above is the lower-level interfaces)

**Comment by jacogr** [comment]
Substrate derivation is not the same as other derivation.

**Comment by SleepingNext** [comment]
So, instead of using BIP 44, it's using sr25519?

**Comment by jacogr** [comment]
So there are differences -

ed25519: only supports hard derivation, it is Substrate-specific implementation with blake2
sr25519: the schnorkell libraries has a strengthened implementation that actually uses the curves optimally

So very different from what is used elsewhere.

**Comment by SleepingNext** [comment]
I'm closing this for now. Thank you, @jacogr.
