### ISSUE TITLE
Better Support on returning Substrate extrinsics error (or documenting it)

### ISSUE THREAD

**Issue by jimmychu0807** [polkadot-js/docs#9]
I am sure the API can do it, because the error is also displayed in the App.

But when using the API itself, how do I know the error being returned when an extrinsic fail? Is this just a lack of documentation or there is no public API for this?

I can try to work on this too.

**Comment by jacogr** [comment]
It has been added to the cookbook a while back - http://localhost:8080/api/cookbook/tx#how-do-i-get-the-decoded-enum-for-an-extrinsicfailed-event

**Comment by faboweb** [comment]
Still a huge issue. Not one explorer is showing proper errors...
