### ISSUE TITLE
TypeError: Cannot read property 'claim' of undefined

### ISSUE THREAD

**Issue by Lawrencehh** [polkadot-js/docs#97]
const utx = api.tx.claims.claim(beneficiary, ethSignature);

console：
TypeError: Cannot read property 'claim' of undefined
    at main (D:/polkadot_test/polkadot_staking_transfer_test/transfer_multi.js:24:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by shawntabrizi** [comment]
This is saying that `claims` is undefined. Are you certain that you are running a Substrate node which has the `claims` pallet?

This would only exist on the Polkadot network.

**Comment by Lawrencehh** [comment]
Thank you！ 
How  to construct "ethSignature"?

**Comment by Lawrencehh** [comment]
The document isn's clear and there are a lot of errors in it.
Importantly , the document doesn't support search function!!
Sometimes, I have to look through all the document and I didn't get the correct answer!

**Comment by jacogr** [comment]
Sorry for your trouble with the docs, there is an enhancement logged to add search, as always, a PR would be very welcome to add that. Additionally if you find oversights, just make a PR.
